apiVersion: v1
kind: Service
metadata:
        name: em-database
spec:
        selector:
           app: database
        ports:
          - protocol: TCP
            port: 7000
            targetPort: 7000
