apiVersion: v1
kind: Service
metadata:
        name: em-backend
spec:
        selector:
           app: backend
        ports:
          - protocol: TCP
            port: 6000
            targetPort: 6000
