apiVersion: v1
kind: Service
metadata:
        name: broker-service
spec:
        selector:
           app: broker
        ports:
          - protocol: TCP
            port: 1883
            targetPort: 1883
