apiVersion: v1
kind: Service
metadata:
        name: cache-service
spec:
        selector:
           app: cache
        ports:
          - protocol: TCP
            port: 4000
            targetPort: 4000
