// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostLoadHandlerFunc turns a function with the right signature into a post load handler
type PostLoadHandlerFunc func(PostLoadParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostLoadHandlerFunc) Handle(params PostLoadParams) middleware.Responder {
	return fn(params)
}

// PostLoadHandler interface for that can handle valid post load params
type PostLoadHandler interface {
	Handle(PostLoadParams) middleware.Responder
}

// NewPostLoad creates a new http.Handler for the post load operation
func NewPostLoad(ctx *middleware.Context, handler PostLoadHandler) *PostLoad {
	return &PostLoad{Context: ctx, Handler: handler}
}

/* PostLoad swagger:route POST /load postLoad

Load data in cache

*/
type PostLoad struct {
	Context *middleware.Context
	Handler PostLoadHandler
}

func (o *PostLoad) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostLoadParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
