// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Backend APIs
//
//  EM Backend server APIs
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 1.1.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
