// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetSearchbyIDHandlerFunc turns a function with the right signature into a get searchby ID handler
type GetSearchbyIDHandlerFunc func(GetSearchbyIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSearchbyIDHandlerFunc) Handle(params GetSearchbyIDParams) middleware.Responder {
	return fn(params)
}

// GetSearchbyIDHandler interface for that can handle valid get searchby ID params
type GetSearchbyIDHandler interface {
	Handle(GetSearchbyIDParams) middleware.Responder
}

// NewGetSearchbyID creates a new http.Handler for the get searchby ID operation
func NewGetSearchbyID(ctx *middleware.Context, handler GetSearchbyIDHandler) *GetSearchbyID {
	return &GetSearchbyID{Context: ctx, Handler: handler}
}

/* GetSearchbyID swagger:route GET /searchbyID getSearchbyId

Return the search result

*/
type GetSearchbyID struct {
	Context *middleware.Context
	Handler GetSearchbyIDHandler
}

func (o *GetSearchbyID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetSearchbyIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetSearchbyIDOKBody get searchby ID o k body
//
// swagger:model GetSearchbyIDOKBody
type GetSearchbyIDOKBody struct {

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this get searchby ID o k body
func (o *GetSearchbyIDOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get searchby ID o k body based on context it is used
func (o *GetSearchbyIDOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetSearchbyIDOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetSearchbyIDOKBody) UnmarshalBinary(b []byte) error {
	var res GetSearchbyIDOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
