// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetSearchbyIDOKCode is the HTTP code returned for type GetSearchbyIDOK
const GetSearchbyIDOKCode int = 200

/*GetSearchbyIDOK Data found

swagger:response getSearchbyIdOK
*/
type GetSearchbyIDOK struct {

	/*
	  In: Body
	*/
	Payload *GetSearchbyIDOKBody `json:"body,omitempty"`
}

// NewGetSearchbyIDOK creates GetSearchbyIDOK with default headers values
func NewGetSearchbyIDOK() *GetSearchbyIDOK {

	return &GetSearchbyIDOK{}
}

// WithPayload adds the payload to the get searchby Id o k response
func (o *GetSearchbyIDOK) WithPayload(payload *GetSearchbyIDOKBody) *GetSearchbyIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get searchby Id o k response
func (o *GetSearchbyIDOK) SetPayload(payload *GetSearchbyIDOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSearchbyIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetSearchbyIDBadRequestCode is the HTTP code returned for type GetSearchbyIDBadRequest
const GetSearchbyIDBadRequestCode int = 400

/*GetSearchbyIDBadRequest Key not found

swagger:response getSearchbyIdBadRequest
*/
type GetSearchbyIDBadRequest struct {
}

// NewGetSearchbyIDBadRequest creates GetSearchbyIDBadRequest with default headers values
func NewGetSearchbyIDBadRequest() *GetSearchbyIDBadRequest {

	return &GetSearchbyIDBadRequest{}
}

// WriteResponse to the client
func (o *GetSearchbyIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetSearchbyIDMethodNotAllowedCode is the HTTP code returned for type GetSearchbyIDMethodNotAllowed
const GetSearchbyIDMethodNotAllowedCode int = 405

/*GetSearchbyIDMethodNotAllowed Method not allowed

swagger:response getSearchbyIdMethodNotAllowed
*/
type GetSearchbyIDMethodNotAllowed struct {
}

// NewGetSearchbyIDMethodNotAllowed creates GetSearchbyIDMethodNotAllowed with default headers values
func NewGetSearchbyIDMethodNotAllowed() *GetSearchbyIDMethodNotAllowed {

	return &GetSearchbyIDMethodNotAllowed{}
}

// WriteResponse to the client
func (o *GetSearchbyIDMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}
