// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetSearchOKCode is the HTTP code returned for type GetSearchOK
const GetSearchOKCode int = 200

/*GetSearchOK OK

swagger:response getSearchOK
*/
type GetSearchOK struct {

	/*
	  In: Body
	*/
	Payload *GetSearchOKBody `json:"body,omitempty"`
}

// NewGetSearchOK creates GetSearchOK with default headers values
func NewGetSearchOK() *GetSearchOK {

	return &GetSearchOK{}
}

// WithPayload adds the payload to the get search o k response
func (o *GetSearchOK) WithPayload(payload *GetSearchOKBody) *GetSearchOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get search o k response
func (o *GetSearchOK) SetPayload(payload *GetSearchOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSearchOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetSearchBadRequestCode is the HTTP code returned for type GetSearchBadRequest
const GetSearchBadRequestCode int = 400

/*GetSearchBadRequest The specified offset is not valid

swagger:response getSearchBadRequest
*/
type GetSearchBadRequest struct {
}

// NewGetSearchBadRequest creates GetSearchBadRequest with default headers values
func NewGetSearchBadRequest() *GetSearchBadRequest {

	return &GetSearchBadRequest{}
}

// WriteResponse to the client
func (o *GetSearchBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetSearchMethodNotAllowedCode is the HTTP code returned for type GetSearchMethodNotAllowed
const GetSearchMethodNotAllowedCode int = 405

/*GetSearchMethodNotAllowed Method not allowed

swagger:response getSearchMethodNotAllowed
*/
type GetSearchMethodNotAllowed struct {
}

// NewGetSearchMethodNotAllowed creates GetSearchMethodNotAllowed with default headers values
func NewGetSearchMethodNotAllowed() *GetSearchMethodNotAllowed {

	return &GetSearchMethodNotAllowed{}
}

// WriteResponse to the client
func (o *GetSearchMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}
