// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostSubmitOKCode is the HTTP code returned for type PostSubmitOK
const PostSubmitOKCode int = 200

/*PostSubmitOK Saved

swagger:response postSubmitOK
*/
type PostSubmitOK struct {
}

// NewPostSubmitOK creates PostSubmitOK with default headers values
func NewPostSubmitOK() *PostSubmitOK {

	return &PostSubmitOK{}
}

// WriteResponse to the client
func (o *PostSubmitOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostSubmitBadRequestCode is the HTTP code returned for type PostSubmitBadRequest
const PostSubmitBadRequestCode int = 400

/*PostSubmitBadRequest The specified key, value pair is invalid (requires strings)

swagger:response postSubmitBadRequest
*/
type PostSubmitBadRequest struct {
}

// NewPostSubmitBadRequest creates PostSubmitBadRequest with default headers values
func NewPostSubmitBadRequest() *PostSubmitBadRequest {

	return &PostSubmitBadRequest{}
}

// WriteResponse to the client
func (o *PostSubmitBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostSubmitMethodNotAllowedCode is the HTTP code returned for type PostSubmitMethodNotAllowed
const PostSubmitMethodNotAllowedCode int = 405

/*PostSubmitMethodNotAllowed Method not allowed

swagger:response postSubmitMethodNotAllowed
*/
type PostSubmitMethodNotAllowed struct {
}

// NewPostSubmitMethodNotAllowed creates PostSubmitMethodNotAllowed with default headers values
func NewPostSubmitMethodNotAllowed() *PostSubmitMethodNotAllowed {

	return &PostSubmitMethodNotAllowed{}
}

// WriteResponse to the client
func (o *PostSubmitMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}
