// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetGetParams creates a new GetGetParams object
//
// There are no default values defined in the spec.
func NewGetGetParams() GetGetParams {

	return GetGetParams{}
}

// GetGetParams contains all the bound params for the get get operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetGet
type GetGetParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: query
	*/
	EmployeeID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetGetParams() beforehand.
func (o *GetGetParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qEmployeeID, qhkEmployeeID, _ := qs.GetOK("employee_id")
	if err := o.bindEmployeeID(qEmployeeID, qhkEmployeeID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindEmployeeID binds and validates parameter EmployeeID from query.
func (o *GetGetParams) bindEmployeeID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("employee_id", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("employee_id", "query", raw); err != nil {
		return err
	}
	o.EmployeeID = raw

	return nil
}
