// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"cache/models"
)

// GetGetOKCode is the HTTP code returned for type GetGetOK
const GetGetOKCode int = 200

/*GetGetOK return employee name

swagger:response getGetOK
*/
type GetGetOK struct {

	/*
	  In: Body
	*/
	Payload *models.Record `json:"body,omitempty"`
}

// NewGetGetOK creates GetGetOK with default headers values
func NewGetGetOK() *GetGetOK {

	return &GetGetOK{}
}

// WithPayload adds the payload to the get get o k response
func (o *GetGetOK) WithPayload(payload *models.Record) *GetGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get get o k response
func (o *GetGetOK) SetPayload(payload *models.Record) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetGetBadRequestCode is the HTTP code returned for type GetGetBadRequest
const GetGetBadRequestCode int = 400

/*GetGetBadRequest Key not found

swagger:response getGetBadRequest
*/
type GetGetBadRequest struct {
}

// NewGetGetBadRequest creates GetGetBadRequest with default headers values
func NewGetGetBadRequest() *GetGetBadRequest {

	return &GetGetBadRequest{}
}

// WriteResponse to the client
func (o *GetGetBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetGetMethodNotAllowedCode is the HTTP code returned for type GetGetMethodNotAllowed
const GetGetMethodNotAllowedCode int = 405

/*GetGetMethodNotAllowed Method not allowed

swagger:response getGetMethodNotAllowed
*/
type GetGetMethodNotAllowed struct {
}

// NewGetGetMethodNotAllowed creates GetGetMethodNotAllowed with default headers values
func NewGetGetMethodNotAllowed() *GetGetMethodNotAllowed {

	return &GetGetMethodNotAllowed{}
}

// WriteResponse to the client
func (o *GetGetMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}
