// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"cache/models"
)

// PostSearchOKCode is the HTTP code returned for type PostSearchOK
const PostSearchOKCode int = 200

/*PostSearchOK Response with 10 key value pair

swagger:response postSearchOK
*/
type PostSearchOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Record `json:"body,omitempty"`
}

// NewPostSearchOK creates PostSearchOK with default headers values
func NewPostSearchOK() *PostSearchOK {

	return &PostSearchOK{}
}

// WithPayload adds the payload to the post search o k response
func (o *PostSearchOK) WithPayload(payload []*models.Record) *PostSearchOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post search o k response
func (o *PostSearchOK) SetPayload(payload []*models.Record) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostSearchOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Record, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PostSearchBadRequestCode is the HTTP code returned for type PostSearchBadRequest
const PostSearchBadRequestCode int = 400

/*PostSearchBadRequest The specified offset is not valid

swagger:response postSearchBadRequest
*/
type PostSearchBadRequest struct {
}

// NewPostSearchBadRequest creates PostSearchBadRequest with default headers values
func NewPostSearchBadRequest() *PostSearchBadRequest {

	return &PostSearchBadRequest{}
}

// WriteResponse to the client
func (o *PostSearchBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostSearchMethodNotAllowedCode is the HTTP code returned for type PostSearchMethodNotAllowed
const PostSearchMethodNotAllowedCode int = 405

/*PostSearchMethodNotAllowed Method not allowed

swagger:response postSearchMethodNotAllowed
*/
type PostSearchMethodNotAllowed struct {
}

// NewPostSearchMethodNotAllowed creates PostSearchMethodNotAllowed with default headers values
func NewPostSearchMethodNotAllowed() *PostSearchMethodNotAllowed {

	return &PostSearchMethodNotAllowed{}
}

// WriteResponse to the client
func (o *PostSearchMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}
