apiVersion: v1
kind: Service
metadata:
        name: em-cache
spec:
        selector:
           app: cache
        ports:
          - protocol: TCP
            port: 4000
            targetPort: 4000
